/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuickbuyRouteImport } from './routes/quickbuy'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OOrderNoRouteImport } from './routes/o.$orderNo'
import { Route as MInboxRouteImport } from './routes/m.inbox'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminPresetsRouteImport } from './routes/admin.presets'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AppProjectIdRouteImport } from './routes/app.project.$id'
import { Route as ApiPublicExportProjectRouteImport } from './routes/api/public/export-project'
import { Route as ApiPublicOrdersOrderNoRouteImport } from './routes/api/public/orders.$orderNo'
import { Route as ApiPublicGSlugPlaceOrderRouteImport } from './routes/api/public/g.$slug.place-order'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickbuyRoute = QuickbuyRouteImport.update({
  id: '/quickbuy',
  path: '/quickbuy',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OOrderNoRoute = OOrderNoRouteImport.update({
  id: '/o/$orderNo',
  path: '/o/$orderNo',
  getParentRoute: () => rootRouteImport,
} as any)
const MInboxRoute = MInboxRouteImport.update({
  id: '/m/inbox',
  path: '/m/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPresetsRoute = AdminPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AppProjectIdRoute = AppProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicExportProjectRoute = ApiPublicExportProjectRouteImport.update({
  id: '/api/public/export-project',
  path: '/api/public/export-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrdersOrderNoRoute = ApiPublicOrdersOrderNoRouteImport.update({
  id: '/api/public/orders/$orderNo',
  path: '/api/public/orders/$orderNo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGSlugPlaceOrderRoute =
  ApiPublicGSlugPlaceOrderRouteImport.update({
    id: '/api/public/g/$slug/place-order',
    path: '/api/public/g/$slug/place-order',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/extension': typeof ExtensionRoute
  '/quickbuy': typeof QuickbuyRoute
  '/settings': typeof SettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/presets': typeof AdminPresetsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/g/$slug': typeof GSlugRoute
  '/m/inbox': typeof MInboxRoute
  '/o/$orderNo': typeof OOrderNoRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/export-project': typeof ApiPublicExportProjectRoute
  '/app/project/$id': typeof AppProjectIdRoute
  '/api/public/orders/$orderNo': typeof ApiPublicOrdersOrderNoRoute
  '/api/public/g/$slug/place-order': typeof ApiPublicGSlugPlaceOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/extension': typeof ExtensionRoute
  '/quickbuy': typeof QuickbuyRoute
  '/settings': typeof SettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/presets': typeof AdminPresetsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/g/$slug': typeof GSlugRoute
  '/m/inbox': typeof MInboxRoute
  '/o/$orderNo': typeof OOrderNoRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/public/export-project': typeof ApiPublicExportProjectRoute
  '/app/project/$id': typeof AppProjectIdRoute
  '/api/public/orders/$orderNo': typeof ApiPublicOrdersOrderNoRoute
  '/api/public/g/$slug/place-order': typeof ApiPublicGSlugPlaceOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/extension': typeof ExtensionRoute
  '/quickbuy': typeof QuickbuyRoute
  '/settings': typeof SettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/presets': typeof AdminPresetsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/g/$slug': typeof GSlugRoute
  '/m/inbox': typeof MInboxRoute
  '/o/$orderNo': typeof OOrderNoRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/export-project': typeof ApiPublicExportProjectRoute
  '/app/project/$id': typeof AppProjectIdRoute
  '/api/public/orders/$orderNo': typeof ApiPublicOrdersOrderNoRoute
  '/api/public/g/$slug/place-order': typeof ApiPublicGSlugPlaceOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/extension'
    | '/quickbuy'
    | '/settings'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/presets'
    | '/admin/users'
    | '/api/chat'
    | '/api/generate-image'
    | '/g/$slug'
    | '/m/inbox'
    | '/o/$orderNo'
    | '/admin/'
    | '/app/'
    | '/api/public/export-project'
    | '/app/project/$id'
    | '/api/public/orders/$orderNo'
    | '/api/public/g/$slug/place-order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/extension'
    | '/quickbuy'
    | '/settings'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/presets'
    | '/admin/users'
    | '/api/chat'
    | '/api/generate-image'
    | '/g/$slug'
    | '/m/inbox'
    | '/o/$orderNo'
    | '/admin'
    | '/app'
    | '/api/public/export-project'
    | '/app/project/$id'
    | '/api/public/orders/$orderNo'
    | '/api/public/g/$slug/place-order'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/extension'
    | '/quickbuy'
    | '/settings'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/presets'
    | '/admin/users'
    | '/api/chat'
    | '/api/generate-image'
    | '/g/$slug'
    | '/m/inbox'
    | '/o/$orderNo'
    | '/admin/'
    | '/app/'
    | '/api/public/export-project'
    | '/app/project/$id'
    | '/api/public/orders/$orderNo'
    | '/api/public/g/$slug/place-order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExtensionRoute: typeof ExtensionRoute
  QuickbuyRoute: typeof QuickbuyRoute
  SettingsRoute: typeof SettingsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  GSlugRoute: typeof GSlugRoute
  MInboxRoute: typeof MInboxRoute
  OOrderNoRoute: typeof OOrderNoRoute
  ApiPublicExportProjectRoute: typeof ApiPublicExportProjectRoute
  ApiPublicOrdersOrderNoRoute: typeof ApiPublicOrdersOrderNoRoute
  ApiPublicGSlugPlaceOrderRoute: typeof ApiPublicGSlugPlaceOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quickbuy': {
      id: '/quickbuy'
      path: '/quickbuy'
      fullPath: '/quickbuy'
      preLoaderRoute: typeof QuickbuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/o/$orderNo': {
      id: '/o/$orderNo'
      path: '/o/$orderNo'
      fullPath: '/o/$orderNo'
      preLoaderRoute: typeof OOrderNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/inbox': {
      id: '/m/inbox'
      path: '/m/inbox'
      fullPath: '/m/inbox'
      preLoaderRoute: typeof MInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/presets': {
      id: '/admin/presets'
      path: '/presets'
      fullPath: '/admin/presets'
      preLoaderRoute: typeof AdminPresetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/project/$id': {
      id: '/app/project/$id'
      path: '/project/$id'
      fullPath: '/app/project/$id'
      preLoaderRoute: typeof AppProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/export-project': {
      id: '/api/public/export-project'
      path: '/api/public/export-project'
      fullPath: '/api/public/export-project'
      preLoaderRoute: typeof ApiPublicExportProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orders/$orderNo': {
      id: '/api/public/orders/$orderNo'
      path: '/api/public/orders/$orderNo'
      fullPath: '/api/public/orders/$orderNo'
      preLoaderRoute: typeof ApiPublicOrdersOrderNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/g/$slug/place-order': {
      id: '/api/public/g/$slug/place-order'
      path: '/api/public/g/$slug/place-order'
      fullPath: '/api/public/g/$slug/place-order'
      preLoaderRoute: typeof ApiPublicGSlugPlaceOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPresetsRoute: typeof AdminPresetsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPresetsRoute: AdminPresetsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppProjectIdRoute: typeof AppProjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppProjectIdRoute: AppProjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ExtensionRoute: ExtensionRoute,
  QuickbuyRoute: QuickbuyRoute,
  SettingsRoute: SettingsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  GSlugRoute: GSlugRoute,
  MInboxRoute: MInboxRoute,
  OOrderNoRoute: OOrderNoRoute,
  ApiPublicExportProjectRoute: ApiPublicExportProjectRoute,
  ApiPublicOrdersOrderNoRoute: ApiPublicOrdersOrderNoRoute,
  ApiPublicGSlugPlaceOrderRoute: ApiPublicGSlugPlaceOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
